### ISSUE TITLE
Once installed and created the tenant I cant register a user

### ISSUE THREAD

**Issue by pedrosilvabos** [andranikbadalyan/Laravel-Multitenant-Boilerplate#1]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'multitenant.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `email` = pedro.silva.bos@gmail.com)

it points to the multitenant.users while it should be pointing to the uuid of the tenant.users

**Comment by andranikbadalyan** [comment]
Hey Pedro,
Just figured out what was the issue, the validation must specify the database when using unique or exists, so in your RegisterConroller.php change the email validation to 
  ```
  /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:tenant.users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }
```
